const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: ' Classic Cheeseburger',
    category: 'lunch',
    price: 13.99,
    img: './images/B.jpg',
    desc: `Juicy beef patty topped with melted cheese, fresh lettuce, tomato, onions, and pickles, served with crispy fries.`,
  },
  {
    id: 3,
    title: 'Salted Caramel Shake',
    category: 'shakes',
    price: 6.99,
    img: './images/Cr.jpg',
    desc: `Rich caramel milkshake with a hint of sea salt, garnished with caramel drizzle and a sprinkle of sea salt flakes.`,
  },
  {
    id: 4,
    title: 'Veggie Omelette',
    category: 'breakfast',
    price: 20.99,
    img: './images/V.jpg',
    desc: `Three-egg omelette filled with sautéed vegetables, topped with melted cheese and served with a side of toast. `,
  },
  {
    id: 5,
    title: 'Grilled Chicken Caesar Salad',
    category: 'lunch',
    price: 22.99,
    img: './images/Gc.jpg',
    desc: ` Grilled chicken breast served on a bed of crisp romaine lettuce, tossed in creamy Caesar dressing, and topped with Parmesan cheese and croutons.`,
  },
  {
    id: 6,
    title: 'Strawberry Banana Smoothie',
    category: 'shakes',
    price: 18.99,
    img: './images/Sb.jpeg',
    desc: ` Refreshing blend of ripe strawberries, sweet bananas, and creamy yogurt, perfect for a healthy and delicious treat.`,
  },
  {
    id: 7,
    title: 'Avocado Toast',
    category: 'breakfast',
    price: 8.99,
    img: './images/Av.jpeg',
    desc: `Toasted artisan bread topped with mashed avocado, cherry tomatoes, red pepper flakes, and a drizzle of olive oil. `,
  },
  {
    id: 8,
    title: 'Margherita Pizza',
    category: 'lunch',
    price: 12.99,
    img: './images/Mp.jpg',
    desc: ` Traditional Italian pizza topped with fresh tomatoes, mozzarella cheese, basil leaves, and a drizzle of olive oil. `,
  },
  {
    id: 9,
    title: ' Chocolate Brownie Shake',
    category: 'shakes',
    price: 16.99,
    img: './images/Cs.jpg',
    desc: ` Creamy chocolate milkshake blended with chunks of fudgy brownie, topped with whipped cream and chocolate sprinkles.`,
  },
];
export default menu;
